title: "Robbie Jakob-Whitworth"
email: hi@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Coach at Major League Hacking, a software developer, a technical consultant
  and I love using GitHub Pages!
baseurl: "/" 
url: "https://robzwolf.github.io/fellowship-site-1/" 
twitter_username: robzwolf
github_username:  robzwolf

sass:
  sass_dir: _sass

icon: ./assets/img/robbie.jpg
